import {indexData,matchNode,ancestorIds,treeRows} from './compression-model.mjs';
const $=id=>document.getElementById(id);
const sides=['source','compressed'];
let catalog=[],data,index,loadSequence=0,profile='budget',selected=null;
let expanded={source:new Set(),compressed:new Set()},queries={source:'',compressed:''},visible={source:[],compressed:[]};
const fmt=n=>Number.isFinite(n)?n.toLocaleString():'—';
const percent=n=>Number.isFinite(n)?`${(n*100).toFixed(1)}%`:'—';
function el(tag,className,text){const element=document.createElement(tag);if(className)element.className=className;if(text!==undefined)element.textContent=text;return element;}
function roots(side){return index[`${side}Roots`];}
function setStatus(text){$('status').textContent=text;}
function writeUrl(){const url=new URL(location.href);url.searchParams.set('doc',data.id);url.searchParams.set('profile',profile);history.replaceState(null,'',url);}
function renderCatalog(){const nav=$('documents');nav.replaceChildren();catalog.forEach((doc,i)=>{const button=el('button','document');button.type='button';button.classList.toggle('active',data?.id===doc.id);button.setAttribute('aria-current',data?.id===doc.id?'page':'false');button.append(el('span','doc-index',String(i+1).padStart(2,'0')),el('span','doc-label',doc.label||doc.id));button.title=doc.label||doc.id;button.addEventListener('click',()=>loadDocument(doc));nav.append(button);});$('document-count').textContent=String(catalog.length);}
function initializeProfile(){if(!data.profiles[profile])profile=Object.keys(data.profiles)[0];$('profile').value=profile;for(const option of $('profile').options)option.disabled=!data.profiles[option.value];index=indexData(data,profile);selected=null;for(const side of sides){expanded[side]=new Set(roots(side));for(const id of roots(side)){for(const child of index[side].get(id)?.children||[])if(index[side].get(child)?.tag!=='head')expanded[side].add(child);}queries[side]='';$(`${side}-search`).value='';}const report=data.profiles[profile].report||{};const sourceN=report.sourceElements??index.source.size,compressedN=report.outputElements??index.compressed.size;$('source-count').textContent=fmt(sourceN);$('compressed-count').textContent=fmt(compressedN);$('node-ratio').textContent=percent(report.nodeRatio??compressedN/sourceN);$('byte-savings').textContent=percent(report.sourceBytes?1-report.outputBytes/report.sourceBytes:NaN);
const failed=[];const walk=(value,path='')=>{if(Array.isArray(value)){value.forEach((v,i)=>walk(v,`${path} ${i}`));return;}if(value&&typeof value==='object'){for(const [k,v]of Object.entries(value)){if((k==='passed'||k==='ok'||k==='valid')&&v===false)failed.push(path||'Preservation audit');else if((/fail|error/i.test(k))&&((Array.isArray(v)&&v.length)||(typeof v==='number'&&v>0)||(typeof v==='string'&&v)))failed.push(`${k}: ${typeof v==='string'?v:JSON.stringify(v).slice(0,350)}`);else walk(v,`${path} ${k}`);}}};walk(report);if(report.sourceRoundTripStable===false)failed.push('Original source changes when reparsed; this is separate from the selected output audit');$('warning').hidden=!failed.length;$('warning').textContent=`Audit warning — ${[...new Set(failed)].join('; ')}. Inspect the affected mappings before relying on this capture.`;
renderTrees();renderDetails();writeUrl();setStatus(`${fmt(sourceN-compressedN)} fewer elements. Click either tree to follow a node across the compression.`);}
async function loadDocument(doc){const sequence=++loadSequence;setStatus(`Loading ${doc.label||doc.id}…`);for(const side of sides)$(`${side}-tree`).replaceChildren(el('p','empty','Loading DOM…'));try{const file=doc.file||`${doc.id}.json`;const url=file.startsWith('data/')?file:`data/compression/${file.replace(/^\.\//,'')}`;const response=await fetch(url);if(!response.ok)throw new Error(`HTTP ${response.status}`);const next=await response.json();if(sequence!==loadSequence)return;data=next;$('document-title').textContent=doc.label||data.label||data.id;$('document-subtitle').textContent=`${data.dataset||'Local example'} / ${typeof data.document==='string'?data.document:'captured document'} · frozen DOM evidence`;renderCatalog();initializeProfile();}catch(error){if(sequence!==loadSequence)return;data=null;index=null;setStatus(`Could not load this capture: ${error.message}`);for(const side of sides)$(`${side}-tree`).replaceChildren(el('p','empty','Capture unavailable. Choose another example or reload the page.'));}}
function renderTrees(){for(const side of sides)renderTree(side);}
function renderTree(side){const tree=$(`${side}-tree`);const scroll=tree.scrollTop;const rows=treeRows(index[side],roots(side),expanded[side],queries[side]);visible[side]=rows;const fragment=document.createDocumentFragment();const chosen=selected?.[`${side}RowId`];const chosenVisible=rows.some(item=>item.node.id===chosen);for(const {node,depth,open,hasChildren}of rows){const row=el('div','tree-row');row.dataset.side=side;row.dataset.nodeId=node.id;row.setAttribute('role','treeitem');row.setAttribute('aria-level',depth+1);row.setAttribute('aria-selected',String(chosen===node.id));row.tabIndex=chosen===node.id||(!chosenVisible&&fragment.childNodes.length===0)?0:-1;row.style.setProperty('--depth',Math.min(depth,12));row.title=`DOM depth ${depth} · ${node.id}`;if(hasChildren)row.setAttribute('aria-expanded',String(open));if(chosen===node.id)row.classList.add(selected.kind==='representative'&&side==='compressed'?'representative':'selected');const toggle=el('button','toggle',hasChildren?(open?'▾':'▸'):'·');toggle.type='button';toggle.tabIndex=-1;toggle.setAttribute('aria-label',`${open?'Collapse':'Expand'} ${node.tag||'node'}`);toggle.disabled=!hasChildren;toggle.addEventListener('click',event=>{event.stopPropagation();toggleNode(side,node.id);});row.append(toggle,el('span','node-tag',`<${node.tag||'node'}>`));if(node.sourceId||node.id)row.append(el('span','node-id',node.sourceId||node.id));const content=(node.text||node.attributes?.['aria-label']||node.attributes?.alt||node.attributes?.title||node.attributes?.placeholder||'').replace(/\s+/g,' ').trim();if(content)row.append(el('span','node-text',content.slice(0,130)));const ledger=index.ledger.get(side==='source'?node.id:node.sourceId);if(ledger?.disposition&&ledger.disposition!=='retained'&&ledger.disposition!=='unchanged')row.append(el('span','node-mark',ledger.disposition));if(side==='compressed'){const a=node.attributes||{};if('data-deferred' in a)row.append(el('span','node-mark',a['data-omitted-items']?`${a['data-omitted-items']} omitted`:'partial'));else if('data-excerpt' in a)row.append(el('span','node-mark','excerpt'));}row.addEventListener('click',()=>selectNode(side,node.id));row.addEventListener('keydown',event=>handleTreeKey(event,side,node.id));fragment.append(row);}tree.replaceChildren(fragment);if(!rows.length)tree.append(el('p','empty',queries[side]?'No nodes match this search. Clear the search to see the tree.':'This profile has no nodes.'));tree.scrollTop=scroll;}
function findRow(side,id){return [...$(`${side}-tree`).querySelectorAll('[data-node-id]')].find(row=>row.dataset.nodeId===id);}
function toggleNode(side,id){expanded[side].has(id)?expanded[side].delete(id):expanded[side].add(id);renderTree(side);findRow(side,id)?.focus({preventScroll:true});}
function selectNode(side,id){selected=matchNode(index,side,id);for(const target of sides){const targetId=selected[`${target}RowId`];if(targetId){for(const ancestor of ancestorIds(index[target],targetId))expanded[target].add(ancestor);if(target!==side){queries[target]='';$(`${target}-search`).value='';}}}renderTrees();renderDetails();for(const target of sides){const targetId=selected[`${target}RowId`];if(targetId){const row=findRow(target,targetId);row?.scrollIntoView({block:'nearest',inline:'nearest'});if(target===side)row?.focus({preventScroll:true});}}setStatus(selected.reason||`${selected.kind} correspondence`);}
function handleTreeKey(event,side,id){const rows=visible[side],pos=rows.findIndex(row=>row.node.id===id),node=index[side].get(id);let target;if(event.key==='ArrowDown')target=rows[Math.min(rows.length-1,pos+1)]?.node.id;else if(event.key==='ArrowUp')target=rows[Math.max(0,pos-1)]?.node.id;else if(event.key==='Home')target=rows[0]?.node.id;else if(event.key==='End')target=rows.at(-1)?.node.id;else if(event.key==='ArrowRight'){if(node.children?.length&&!expanded[side].has(id)){event.preventDefault();toggleNode(side,id);return;}target=node.children?.[0];}else if(event.key==='ArrowLeft'){if(expanded[side].has(id)&&node.children?.length){event.preventDefault();toggleNode(side,id);return;}target=node.parent;}else if(event.key==='Enter'||event.key===' '){event.preventDefault();selectNode(side,id);return;}else return;event.preventDefault();if(target)findRow(side,target)?.focus({preventScroll:false});}
function detailBlock(container,label,value){container.append(el('span','detail-label',label));const text=typeof value==='string'?value:JSON.stringify(value,null,2);const pre=el('pre','',text.length>2400?`${text.slice(0,2400)}\n…`:text);container.append(pre);if(text.length>2400){const button=el('button','show-full',`Show full ${label.toLowerCase()} (${fmt(text.length)} characters)`);button.type='button';button.addEventListener('click',()=>{pre.textContent=text;button.remove();});container.append(button);}}
function renderDetails(){const badge=$('match-badge');badge.textContent=selected?({exact:'Exact source link',representative:'Representative · not exact',absent:'No counterpart',ambiguous:'Ambiguous mapping'}[selected.kind]||selected.kind):'Select a node';$('match-explanation').textContent=selected?`${selected.reason||''}${selected.disposition?` Disposition: ${selected.disposition}.`:''}`:'Follow a node across both trees to inspect its text, attributes, and compression decisions.';for(const side of sides){const box=$(`${side}-detail`);box.replaceChildren(el('h4','',side==='source'?'FULL DOM':'COMPRESSED DOM'));const node=selected&&index[side].get(selected[`${side}RowId`]);if(!node){box.append(el('p','',selected?'No corresponding node in this view.':'No node selected.'));continue;}detailBlock(box,'Node',`<${node.tag}> ${node.id}${node.sourceId?` · source ${node.sourceId}`:''}`);detailBlock(box,'Text',node.text||'(No direct text)');detailBlock(box,'Attributes',node.attributes||{});}if(selected){const ledger=index.ledger.get(selected.sourceId);if(ledger?.reasons?.length)detailBlock($('compressed-detail'),'Compression decisions',ledger.reasons);}}
$('profile').addEventListener('change',()=>{profile=$('profile').value;if(data)initializeProfile();});for(const side of sides){let timer;$(`${side}-search`).addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{if(!index)return;queries[side]=$(`${side}-search`).value;renderTree(side);},140);});document.querySelector(`[data-collapse="${side}"]`).addEventListener('click',()=>{if(!index)return;expanded[side]=new Set();renderTree(side);});}
try{const response=await fetch('data/compression/catalog.json');if(!response.ok)throw new Error(`HTTP ${response.status}`);const result=await response.json();catalog=Array.isArray(result)?result:result.documents;if(!catalog?.length)throw new Error('The collection contains no documents.');const params=new URLSearchParams(location.search);profile=params.get('profile')||'budget';renderCatalog();const initial=catalog.find(doc=>doc.id===params.get('doc'))||catalog.find(doc=>/nasa/i.test(doc.id+' '+doc.label))||catalog[0];await loadDocument(initial);}catch(error){$('document-title').textContent='Collection unavailable';$('documents').replaceChildren(el('p','empty','No examples loaded.'));setStatus(`Unable to open the collection: ${error.message}`);for(const side of sides)$(`${side}-tree`).replaceChildren(el('p','empty','Serve this page with the local inspector server and ensure the compression data has been built.'));}
